# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and, the first terms will be:
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Define variables to store the first two terms of the sequence
a = 1
b = 2

# Define a variable to store the sum of the even-valued terms
even_sum = 0

# Loop through the sequence until the value of b exceeds 4 million
while b <= 4000000:
    # Check if the value of b is even
    if b % 2 == 0:
        # If it is, add it to the even_sum variable
        even_sum += b
    
    # Calculate the next term in the sequence by adding a and b
    c = a + b
    
    # Update the values of a and b to prepare for the next iteration of the loop
    a = b
    b = c

# Print the sum of the even-valued terms
print(even_sum)
